version: '3.4'

services:
  concerts.api:
    image: ${DOCKER_REGISTRY-}concertsapi
    build:
      context: .
      dockerfile: Concerts.API/Dockerfile
    links:
      - database
    depends_on:
      - "database"
    networks:
      - mynetwork

  database:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "12345abcd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - database-data:/var/opt/mssql/data
    networks:
      - mynetwork
volumes:
  database-data: # named volumes can be managed easier using docker-compose

networks:
  mynetwork:
     driver: bridge